### PR TITLE
New Redesign

### PR DESCRIPTION
**Pull request by aaronUnosquare**
As part of the marketing request for the cycle 5, we're redesigning some of the [telepresence.io](https://www.telepresence.io/) pages.

Here's the list of the pages that will be redesigned:

- [x] About
- [x] Join the Community
- [x] Case Studies (Home)
- [x] Case Studies (Template)
- [x] Case Studies (for Bitnami)
- [x] Main menu
- [x] Home

Preview URLs: 
- https://deploy-preview-172--telepresence.netlify.app/
- https://deploy-preview-172--telepresence.netlify.app/about/
- https://deploy-preview-172--telepresence.netlify.app/community/
- https://deploy-preview-172--telepresence.netlify.app/case-studies/
- https://deploy-preview-172--telepresence.netlify.app/case-studies/engel-volkers/
- https://deploy-preview-172--telepresence.netlify.app/case-studies/bitnami/

For more information about this request, please visit the [Telepresence.io redesign #2147 issue](https://github.com/datawire/getambassador.io/issues/2147).

### CODE REVIEW

**Comment by jleetkd** [comment]
@aaronUnosquare Great start, I have a few comments:

1. Can you please make all **header** and **sub-header fonts "Inter"**. Currently the font is set to "Source Sans Pro"
Screen Shot 2022-09-28 at 11 16 21 AM

2. Can you **increase the font size of the header** in "Case Studies" to match the rest of the headers?  the font size should be set at **58px**.
Screen Shot 2022-09-28 at 11 19 58 AM

**Comment by jleetkd** [comment]
@aaronUnosquare Looks great, I just have a few comments.  The first 2 comments are for the entire site (specifically navigation and the sub-navigation below).  The last comment is in regards to the About page.

1. Can you please **match the weight of the fonts for the Top Navigation that are in my Figma design**?  The font weight looks a little too thick in the Preview Link.  The **top screen shot** is of the **Preview Link**, the **bottom screen shot** is of the **Figma file**.
Screen Shot 2022-10-05 at 12 00 47 PM
Screen Shot 2022-10-05 at 12 00 55 PM

2. Can you **remove the sub-navigation at the bottom of every page**?  Since the Top Navigation is sticky, we do not need this section.
Screen Shot 2022-10-05 at 12 10 22 PM

3. In the About Us page, can you **align the content with the left and right margins**?
Screen Shot 2022-10-05 at 12 09 01 PM

**Comment by kelseyevans** [comment]
In the last paragraph "To find out more about the Telepresence Architecture, check out the docs or join us in [Slack](http://a8r.io/slack)." please make "the docs" a hyperlink to https://www.getambassador.io/docs/telepresence/latest/reference/architecture/.

**Comment by kelseyevans** [comment]
change capitalization in subheader to OpenShift

**Comment by kelseyevans** [comment]
Under Accelerate Your Inner Dev Loop "as if your developing locally" --> "as if you're developing locally"

**Comment by kelseyevans** [comment]
In the site nav "Github" should be capitalized "GitHub"

**Comment by kelseyevans** [comment]
Remove the button labeled "quickstart page" and link to the quickstart page only in the button labeled "Get Started"

**Comment by kelseyevans** [comment]
On the About page, update copy to 

Telepresence is an open source tool for Kubernetes application developers that lets you run a single service locally while connecting that service to a remote Kubernetes cluster.

Telepresence is a CNCF sandbox tool built by the team at [Ambassador Labs](https://www.getambassador.io/), the creators of Emissary-ingress (Kubernetes-native API gateway powered by Envoy Proxy). The team at Ambassador Labs is committed to helping development teams build faster & ship safer on Kubernetes. 

We welcome all community contributions. If you find a bug or a mistake in the documentation, you can help us out by submitting an issue or a pull request with a fix. If you have questions, join our active [Slack community](HTTP://a8r.io/slack) or [contact us](https://www.getambassador.io/contact-us) about paid support plans.

**Review by leocontrerasn — APPROVED** [review]

**Pull request merged**
