### PR TITLE
Bring in the new demo-node from getambassador.io

### PR DESCRIPTION
**Pull request by josecv**
Signed-off-by: Jose Cortes <josecortes@datawire.io>

### CODE REVIEW

**Comment by LukeShu** [comment]
I get  Zip file instead of just the bare kubeconfig.yaml that I get from getambassador.io?

**Comment by josecv** [comment]
> I get Zip file instead of just the bare kubeconfig.yaml that I get from getambassador.io?

ah good catch i must've copied the wrong link

**Comment by donnyyung** [comment]
When I go through the quick start, in `testing our fix` step 1, I see: 
```
$ telepresence login --apikey $APIKEY
```
but on getambassador.io I get
```
$ telepresence login --apikey witharealapikey
```

Additionally, the netlify preview prompted me to log into `beta-app.datawire` whereas getambassador had me log into prod.. I'm not sure if that's an issue with the code or just how things are expected to work in netlify, we probably should ask the docs / growth team?.. I can take a deeper look once I'm finished dealing with the incident but wanted to raise these things I was seeing in case they trigger any context you have.

**Comment by josecv** [comment]
@donnyyung i think once you login the apikey should update -- at least it does for me

as for the staging URL thing -- yea, there's logic that checks if you're on telepresence.io and if so sends you to prod, otherwise to staging

**Comment by donnyyung** [comment]
@josecv ah it didn't update for me but that's maybe bc I used my personal github team instead of the ambassador one, I'll log out and try again once we have a new preview url

**Review by donnyyung — APPROVED** [review]
LGTM. the login still wasn't working for me, but I don't think that's an issue with the code / potentially just an issue with my login setup with the beta cloud, I'll try again once this is deployed.

**Pull request merged**
